### PR TITLE
add volts to feed

### PR DESCRIPTION
**Pull request by lincomatic**
allow volts to be sent to feed if valid

### CODE REVIEW

**Comment by glynhudson** [comment]
Ah nice, thanks 👍 

The current openevse hardware does not have a volt meter. What hardware are you using the does have a volt meter?

**Comment by lincomatic** [comment]
One of my EVSEs uses Nick Sayer's OpenEVSE II hardware. He sent me one to develop compatible firmware. It only has some minor changes to the code due to the voltmeter and a different implementation of the AC test pins.

https://www.tindie.com/products/nsayer/openevse-ii/

I've actually been looking into a voltmeter add-on for OpenEVSE, but haven't yet had the time to get it working.

**Comment by lincomatic** [comment]
I get brown outs a lot in my house... the voltage actually drops all the way down to below 210V sometimes! So I use my EVSE w/ emoncms to log my line voltage.

**Comment by glynhudson** [comment]
> I get brown outs a lot in my house... the voltage actually drops all the way down to below 210V sometimes! So I use my EVSE w/ emoncms to log my line voltage.

Oh dear, where do you live? I use our emonPi to monitor VRMS it never goes below about 220V. 

selection_189

It's interesting to note that when EVSE switches on this pulls the voltage down. This is expected

selection_190

**Pull request merged**
