### PR TITLE
OpenEVSE GUI

### PR DESCRIPTION
**Pull request by jeremypoulter**
These are the changes to add a GUI for OpenEVSE, see #34.

This following features have been implemented;
- Partial OpenEVSE JavaScript library, #38 
- Implements setting the service level and current capacity 
- Updating of the charge and time limits 
- Setting of the delay timer
- Switch between sleep/enabled
- Setting the time
- Reboot the OpenEVSE
- Added Developer Mode to show RAPI tab and switches to enable/disable tests

### CODE REVIEW

**Comment by jeremypoulter** [comment]
I think this is feature complete now, I just need to do some optimisations for when accessing via openevse.local, currently each RAPI call takes ~2 seconds, the majority of that on mDNS resolution (~160ms when accessing via IP).

**Comment by glynhudson** [comment]
Wops I just wanted to push a little typo fix to this PR and seem to accidently pushed to a new branch called `jeremypoulter-OpenEVSE_GUI` instead. Is this a problem? Could we just merge the jeremypoulter-OpenEVSE_GUI branch when we're ready? Is it possible for me to add comitts to this PR?

https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/commit/b5a0cc31413d189a91fc3e128c8df6071a99b932

**Comment by glynhudson** [comment]
Just been testing, few little things..in no particular order

GUI is taking shape nicely, good work 👍 

1. Could the GUI by made the default landing page? Do you agree this is a good idea?  
2. I can't see option in the GUI to set energy limit, has this been added? 
3. sometimes there are big spaces between html GUI boxes

4. After entering Emoncms & MQTT details the enable checkboxes are still present and services don't connect. I can see in the debug op that the settings have been saved:

**Update: This has now been fixed by checking the checkbox and hitting save for the 2nd time**

```

OpenEVSE WiFI 1383250
Firmware: 3.1.0
Free: 30824
Loading config
Got 'xxxxxx' 194 == 194 @ 0:32
Got 'xxxxxx' 238 == 238 @ 32:64
Got 'API-KEY' 233 == 233 @ 96:32
Got 'emonpi/emoncms' 203 == 203 @ 128:45
Got 'openevse' 145 == 145 @ 173:32
Got '' 128 == 128 @ 438:60
Got 'emonpi' 144 == 144 @ 205:45
Got 'openevse' 145 == 145 @ 250:32
Got 'emonpimqtt' 140 == 140 @ 282:32
Got 'emonpimqtt2016' 137 == 137 @ 314:64
Got 'solar' 227 == 227 @ 378:30
Got '' 128 == 128 @ 408:30
Got '' 255 == 128 @ 498:16
Using default ''
Got '' 255 == 128 @ 514:16
Using default ''
Got '' 255 == 128 @ 530:10
Using default ''
Got '030000'  131 == 131
After config_load_settings: 30808
Connecting to SSID: xxxxx
Connected, IP: 192.168.0.115
```
Emoncms enabled is still false even though tick box has been enabled and saved: 
```
{"firmware":"3.11.3","protocol":"1.0.3","espflash":"4194304","version":"3.1.0","diodet":"0","gfcit":"0","groundt":"0","relayt":"0","ventt":"0","tempt":"0","service":"2","l1min":"-","l1max":"-","l2min":"6","l2max":"80","scale":"220","offset":"0","gfcicount":"3","nogndcount":"0","stuckcount":"0","kwhlimit":"0","timelimit":"0","ssid":"xxxxx","emoncms_enabled":false,"emoncms_server":"emonpi/emoncms","emoncms_node":"openevse","emoncms_fingerprint":"","mqtt_enabled":false,"mqtt_server":"emonpi","mqtt_topic":"openevse","mqtt_user":"emonpimqtt","mqtt_solar":"solar","mqtt_grid_ie":"","www_username":"","ohm_enabled":false,"divertmode":"1"}
```

**Comment by jeremypoulter** [comment]
@glynhudson strictly speaking you should raise a PR on my fork, but I can just pull the change in and grant you access to commit to my fork, then those changes will just show up in this PR.

**Comment by jeremypoulter** [comment]
> 1. Could the GUI by made the default landing page? Do you agree this is a good idea?

With the WiFi portal this probably makes sense

> 2. I can't see option in the GUI to set energy limit, has this been added?

It is the 'Charge limit' entry, to match the LCD, or have I missed something? Also Charge limit and Time limit only show up when connected, as per the LCD.

> 3. sometimes there are big spaces between html GUI boxes

Yeah, this happens on all screens to some extent. Is to do with the float layout, I will have a look and see if there is anything that can be done short of a complete redesign.

> 4. After entering Emoncms & MQTT details the enable checkboxes are still present and services don't connect. I can see in the debug op that the settings have been saved

Will check this out

**Comment by glynhudson** [comment]
Few other little issues 

- After connecting to a Wifi network, a reboot is required before I can load the webpage. This is not a problem if you can force a reboot after Wifi connection? This would also turn off AP?
- I can't see to turn off `Temperature Monitoring:` or `Vent Required:` checks via the UI. However, this not an issue. I while back I talked to Chris about this and due to the possible safety implications I don't think users should be able to disable safety checks via the GUI. These should be manual LCD only operations. Please could you remove the toggles. Sorry, should have mentioned this earlier. I know it's still possible via RAPI however its much too easy to accidentally toggle a UI toggle and not realise!

**Comment by glynhudson** [comment]
Setting charger, time limit and charge limit all seems to work great. This is awesome! :+1: 

Few more minor things I notice on the UI. Would you prefer me to open issues or continue to post here for issues regarding the GUI? 

- [ ] After entering a charge limit (kwh) there is no enter button, I had to Sleep then Enable charging to see the little energy symbol on the LCD. Is this due to https://github.com/lincomatic/open_evse/issues/65? Even if the LCD does not update having some sort of confirmation that the setting has been set on the GUI would improve UX. 

- [ ] Setting the charge limit on the LCD seems to crash the webserver. Tried twice with same issue. After ESP reboot the correct energy limit it shown on the GUI. Same issue with time limit.  

- [ ] The 'Disable' button moves position, minor issue but did cause me to hit the wrong button one a few times!

selection_077
selection_076

- I know you used the word 'sleep' and 'enable' to emulate the OpenEVSE, however 'pause' and 'resume' would be more user friendly. What do you think @chris1howell 
- I'm not sure if 'Disable' button is needed? Does it do anything more than Sleeping @chris1howell ? 

For the benefit of other devs, this is what the GUI looks like so far:

openevse

**Comment by jeremypoulter** [comment]
> Would you prefer me to open issues or continue to post here for issues regarding the GUI?

Here is fine, just put the check boxes so I can track them.

**Comment by chris1howell** [comment]
*   I'm not sure if 'Disable' button is needed? Does it do anything more than Sleeping @chris1howell<https://github.com/chris1howell> ?

Disable will stop charging and send the station to an error start (pilot to negative DC)
Sleep will stop sharging and send station to a not ready to provide power (pilot to positive DC)

From the User Interface, I would say only Sleep is needed.

On Thu, Jul 27, 2017 at 12:40 PM, Jeremy Poulter <notifications@github.com<mailto:notifications@github.com>> wrote:

Would you prefer me to open issues or continue to post here for issues regarding the GUI?

Here is fine, just put the check boxes so I can track them.

**Comment by jeremypoulter** [comment]
> After entering a charge limit (kwh) there is no enter button, I had to Sleep then Enable charging to see the little energy symbol on the LCD. Is this due to lincomatic/open_evse#65?
Yes, the lack of update is related to lincomatic/open_evse#65

**Comment by jeremypoulter** [comment]
> After connecting to a Wifi network, a reboot is required before I can load the webpage. This is not a problem if you can force a reboot after Wifi connection? This would also turn off AP?

I think this should be broken out in to a new issue of generally improving the initial setup. I don't think it is specifically related to the OpenEVSE GUI

**Comment by jeremypoulter** [comment]
> Setting the charge limit on the LCD seems to crash the webserver. Tried twice with same issue. After ESP reboot the correct energy limit it shown on the GUI. Same issue with time limit.

I can't reproduce this can you give more details, log, .elf file?

**Comment by jeremypoulter** [comment]
> sometimes there are big spaces between html GUI boxes

I managed to fix this, however all the elements in the Charge Options are always shown rather than being hidden.

image

vs 

image

The fundamental problem is the combination of the different size blocks and trying to keep the right hand blocks near the top when in a single column.

There does not look to be a CSS only way to do this. The only reasonable way to get the desired effect is to use a JS library like [masonry](https://github.com/desandro/masonry), but that had issues with the tabs and needs some more extensive re-work of the UI.

The other option is to do something similar to emonESP and have all the content of the right hand side shift to under all the left hand side content.

**Comment by glynhudson** [comment]
Just tested, layout looks much better now. Not nearly as much whitespace

**Pull request merged**
