### PR TITLE
platformio on osx

### PR DESCRIPTION
**Pull request by joverbee**
changes that I needed to get it to compile on a fresh install of platformio on a mac.

### CODE REVIEW

**Comment by joverbee** [comment]
addresses #issue 128

**Comment by joverbee** [comment]
solve #107, but was unable to disentangle the 2 commits (just discard the changes in platformio.ini and diverter.cpp as they might be osx specific)

**Comment by jeremypoulter** [comment]
Nah not OS specific, I had to make similar changes, but had not gotten
around to creating a PR as I did exactly the same thing and bundled the
compilation fixes in with other changes ;-) as a said not a big issue for
these small changes. Good work.

**Comment by glynhudson** [comment]
The ESP Async WebServer has indeed changed it's name to include spaces. The changes were already in the master branch. I've just merged into stable. I'll close this PR since I see the other changes have been broken out into your other PR's. Thanks

**Pull request closed without merging**
