### PR TITLE
Divert mode back-port

### PR DESCRIPTION
**Pull request by jeremypoulter**
Back-port of the PV divert changes from the ESP32 version ([ESP32 V3.2.0 change log](https://github.com/OpenEVSE/ESP32_WiFi_V3.x/releases/tag/3.2.0)), along with a few other fixes/improvements

- PV Divert changes
- Updates to save the config as a JSON block
- Python 3 fixes
- Latest GUI

### CODE REVIEW

**Comment by glynhudson** [comment]
Merged to `new-divert` branch for tested

**Comment by glynhudson** [comment]
Nice work, this back port contains a lot more than just the new solar PV divert code. I see NTP time, VRMS MQTT and other little tweaks has also made it over. Nice work both these features work great on the ESP2866 :+1: 

I tested with a fully erased ESP8266, I will test upgrading separately. 

Things I've noticed so far: 
1. Saving the Emoncms service hostname doesn't work, when I save a hostname e.g `http://emonpi` then look at output of  /config the new hostname has not saved. It still shows the default `emoncms_server: "https://data.openevse.com/emoncms",`. `emoncms_node` saves correctly. 
2. Hostname is `openevse-000`, I think we should just keep the hostname as it was as just `http:/openevse` to avoid confusing users who have been using their existing units with this default hostname. 
4. After fresh reboot Eco Mode is enabled even though it had never been enabled previously, the UI toggle was showing 'Normal Mode' however /status was showing `divertmode: 2,`. When  
5. When EcoMode is enabled with Grid IE charging does not pause even if there is significant import from the Grid for a period of time. The same issue is present when Solar PV gen is selected and thre is 0W of solar PV Gen, charging does not pause:

Grid IE
Screenshot from 2020-06-26 22-34-24 

Solar PV Gen
Screenshot from 2020-06-26 22-36-28

Is it possible to make available those simulation graphs? I forgot to screenshot them. They would be useful to compare alongside real word testing for comparison.

**Comment by jeremypoulter** [comment]
Hum... You loot to have merged anyway!

NTP should not be there, no support in the backend for that. Will have to take a look at all the other issues

Jeremy

**Comment by glynhudson** [comment]
I merged to `new-divert` branch since I figured this would be easier for testing. Sorry for the confusion.

The good news is that it's been running reliably for the past 4 days, the ESP8266 seem to be handling the extra load well. The interface seems to load just as fast as on the ESP32. 

Thanks

**Pull request merged**
