### PR TITLE
RFC: Initial version of HTML app builder

### PR DESCRIPTION
**Pull request by jeremypoulter**
This is an initial version of code to combine and minify the HTML, CSS and JS.

The idea is that, when minified and combined, there will be less resources used on the ESP and lower memory usage.

This will also allow config.js to be split up in to multiple files and maybe allow conditional building to merge the code base with EmonESP, etc.

On the downside the HTML now has to be 'compiled' which can slow down development.

The minifying is done mostly in pure Python and intergrated in to the PlatformIO build process so no additional instilation steps are required.

The exception to this is the JS minification which is done using a web service (the Python minifyer is broken) so you need to be online when building.

### CODE REVIEW

**Comment by glynhudson** [comment]
Fantastic, I've just tested and it seems to work ok for me. I'll report back regarding performance.

Is there any way to un-minify the html / css for dev? 

Do you want me to leave this PR open? Is it a WIP?

**Comment by jeremypoulter** [comment]
Yeah, leave it open for now, there are a few things I want to try and
improve (eg a dev mode as you indicate)

**Comment by glynhudson** [comment]
Would it be possible to keep the working copy in the git repo as un-minified then the minification process takes place on platformio compile / upload and stored in a special folder.  

This is how Jekyll static html generator from markdown works, the markdown files is committed to the repo then Jekyll is ran to generate the static HTML which is stored in a `_deploy` folder ready to be deployed via a web server. We've got Travis CI setup to automatically run Jekyll whenever a change is committed to the markdown files in the git repo.

**Comment by glynhudson** [comment]
I've been doing some testing today and noticed this PR seems have created some layout issues when the page is viewed on desktop:
 
selection_103

I'm also still experiencing the page hanging issues, especially if the unit has been left running for a while e.g. overnight. The following morning it seems to take a number of refreshes to load the page. I'm not sure if this is related, but opening the Chrome dev console seems to help as I believe this clears the page cache. Once the dev console is open the page seems to load much more reliably. Which is annoying sine I was trying to capture the network activity when the page hangs!

**Comment by jeremypoulter** [comment]
> Would it be possible to keep the working copy in the git repo as un-minified then the minification process takes place on platformio compile / upload and stored in a special folder.

The unminified version is in src/html, I kept the minified files in src/data to maintain Arduino IDE compatibility, however I am not worried about breaking that if need be.

> I've been doing some testing today and noticed this PR seems have created some layout issues when the page is viewed on desktop:

Thanks, I will look in to those issues

> I'm also still experiencing the page hanging issues

That is expected, this is only part of the fixes I am working on.

**Comment by glynhudson** [comment]
>The unminified version is in src/html

Ah, that's great. Sorry I had not notices this.

**Comment by glynhudson** [comment]
closed since these commits are included in https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/pull/87

**Pull request merged**
