### PR TITLE
to correct elapsed display

### PR DESCRIPTION
**Pull request by realdesilets47**
to correct elapsed display after 29 seconds and after 29 minutes.
prevent to pass from 29 minutes to 1:30 in one minutes.

### CODE REVIEW

**Comment by glynhudson** [comment]
Is there a reason this PR was closed? I was about to test it. Is this still an issue?

**Comment by realdesilets47** [comment]
No,  I am new on GITHUB and i do know completely how it works.

 

I tested my 3 lines modifications on my openevse and it works fine.  

 

Does i need to reopen this PR to permit you to test it ?

 

Thanks

 

Réal.

 

 

 

De : Glyn Hudson [mailto:notifications@github.com] 
Envoyé : 22 février 2019 12:08
À : OpenEVSE/ESP8266_WiFi_v2.x
Cc : realdesilets47; State change
Objet : Re: [OpenEVSE/ESP8266_WiFi_v2.x] to correct elapsed display (#214)

 

Is there a reason this PR was closed? I was about to test it. Is this still an issue?

**Comment by KMacros** [comment]
I am new to github and using a macbook so I haven't been able to implement a solution for issue #213 which is the same problem. The rounding causes the time to jump around the half fraction point and using trunc or as realdesilets47 is using the floor which for positive values works the same as truncate.  I'd be curious to see if the compiled code for truncate compared to floor would show any reason to choose one over the other.

**Comment by glynhudson** [comment]
Thanks :+1:

**Comment by KMacros** [comment]
I downloaded 2.8.0 binary from release link https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/releases and uploaded using the web page.  The versions show 4.8.0 for openevse and 2.8.0 for OpenEVSE WiFi. The time display while charging still exhibits the rounding behavior.  I believe I have the correct binary loaded since I see the new version 2.8.0 from the above release link.   Adding a screenshot below.

**Comment by jeremypoulter** [comment]
I think the addition of #208 in the same release would have removed the fix :(

@glynhudson Can you do a new release when #222 is merged?  This should add back the fix.

**Comment by KMacros** [comment]
I downloaded 2.8.0 binary from release link https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/releases and uploaded using the web page.  The versions show 4.8.0 for openevse and 2.8.0 for OpenEVSE WiFi. The time display while charging still exhibits the rounding behavior.  I believe I have the correct binary loaded since I see the new version 2.8.0 from the above release link.   Adding a screenshot below.

**Comment by KMacros** [comment]
Looks like my browser fooled me into a double post.  I thought I had commented and apologize for duplicate post.

**Comment by glynhudson** [comment]
Ok thanks, I've updated 2.8.0 release (it's still in pre-prerelease). 

@KMacros please could you try to download V2.8.0 from the releases page and updated and test again? 

Thanks.

**Comment by KMacros** [comment]
Will do and I’ll reply via email for simplicity.

**Comment by KMacros** [comment]
I have verified the rounding issue is resolved.  I had to upload the binary twice as I'm not sure when the firmware is updated when the version number remains the same.  I generated MD5 hashes for both files and confirmed the binary files are different.  The first upload did not update the code so I closed the web page, powered down the openEVSE for a minute, opened new OpenEVSE browser window, selected the binary, update, get OK back after several seconds and then waited for 5 additional minutes.  I then plugged in charge cable and the timer display is no longer rounding. Thank you for your patience and follow up.
Best Regards,Keith

    On Tuesday, March 19, 2019, 12:20:58 PM EDT, Glyn Hudson <notifications@github.com> wrote:  
 
 
Ok thanks, I've updated 2.8.0 release (it's still in pre-prerelease).

@KMacros please could you try to download V2.8.0 from the releases page and updated and test again?

Thanks.

**Pull request merged**
