### PR TITLE
Fixes to master

### PR DESCRIPTION
**Pull request by sandeen**
A handful of fixes
- Some typos that don't matter much
- Fix call to Vcc detection so it works properly
- Fix some unused element IDs in javascript by using them in html: Vcc, amps, flash size (these broke rendering)
- Update energy totals & faults in the main loop rather than only at bootup

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks for moving this PR to this new repo. Lots of good fixes here. 

What are your thoughts on reporting ESP Vcc value? Is this a useful metric to report? I have never found it useful, interested to hear your thoughts. I'm keen to optimise as much as possible since we're hitting some performance issues.

**Comment by sandeen** [comment]
I'm happy to drop any of the metrics, I wasn't sure if fixes like this should go towards the "display each element ID that's defined" or "drop unused element IDs altogether."

I've never really seen it change, to be honest, and if it did I wouldn't know what to do with it, so I'm perfectly happy to drop it.  :)  (That said, I don't know if it's a performance hit or not, but sure - keep the cruft out is always a good plan).

**Comment by sandeen** [comment]
So, I'm not used to the github workflow.  Should I rebase this branch with Vcc removed altogether, if that's the preference?

Thanks,
-Eric

**Comment by glynhudson** [comment]
Let's remove it.

Now the pull request is open any commits you make to your branch will be
included in the pr. Let me know when you have made a pr to remove vcc and
I'll get it merged.

Thanks again

- sent from my mobile device

**Comment by sandeen** [comment]
Ok, well, I'm not wedded to Vcc.  The current PR includes a commit to remove it.

Thanks,
-Eric

**Comment by sandeen** [comment]
I added one more commit, to scale the raw values on the Status tab to something more meaningful.
I'll stop for now until you have a chance to review.  Thanks!

**Comment by chris1howell** [comment]
Don't stop... Love the activity.
Think you might be able to add the ability to adjust current in javascript?  thinking a slider or up down arrows from current min to current max that sends /r?rapi=%24SC+**xx**

**Comment by sandeen** [comment]
I meant stop until you get a chance to merge it, didn't want to keep updating the branch while you reviewed it.  ;)  I had been looking at javascript sliders to set time & kwh limits, too.

What I really wanted to try to clean up next is the rapi loop, because the slow updates are a bit painful.  And there are even a few things which still are only updated on init, and not in the loop (like the aforementioned limits).

I'm playing with a function to encapsulate the token parsing for the response, which eliminates a lot of cut & paste code.  Then I want to think about how to keep the loop fast but also efficient - I'm just spooked by Glyn's report of http firmware update problems, I don't know what to make of that.  I've also seen occasional many-second stalls on the web page, and I have no idea what's causing them.

I guess the next thing I wanted to play with was trying OTA firmware & fs updates, because running out to the garage for testing updates is a PITA.  Do you have any good mechanism for faking out RAPI responses on a test board?

Anyway, sure, can add sliders to the TODO.  ;)

**Comment by chris1howell** [comment]
Great, sounds like a lot of good stuff.

OTA firmware is easy, its the file system that will require more work. It may be possible to modify the update library to upload both a firmware.bin and filesystem.bin to the correct memory locations.

For RAPI, I use a spare board powered by a programmer with all the tests disabled. I have a few boards without power supplies that would work. I will send you one.

On Tue, May 2, 2017 at 10:17 AM, Eric Sandeen <notifications@github.com<mailto:notifications@github.com>> wrote:

I meant stop until you get a chance to merge it, didn't want to keep updating the branch while you reviewed it. ;) I had been looking at javascript sliders to set time & kwh limits, too.

What I really wanted to try to clean up next is the rapi loop, because the slow updates are a bit painful. And there are even a few things which still are only updated on init, and not in the loop (like the aforementioned limits).

I'm playing with a function to encapsulate the token parsing for the response, which eliminates a lot of cut & paste code. Then I want to think about how to keep the loop fast but also efficient - I'm just spooked by Glyn's report of http firmware update problems, I don't know what to make of that. I've also seen occasional many-second stalls on the web page, and I have no idea what's causing them.

I guess the next thing I wanted to play with was trying OTA firmware & fs updates, because running out to the garage for testing updates is a PITA. Do you have any good mechanism for faking out RAPI responses on a test board?

Anyway, sure, can add sliders to the TODO. ;)

**Comment by lincomatic** [comment]
I have RAPI interface code to contribute. Don't have time to figure out how to integrate it into your codebase. Who should I email it to?

**Comment by chris1howell** [comment]
Awesome lincomatic, email it to me and I will work on it and/or forward to Eric if he wants to take a shot at it.

On May 2, 2017 4:48 PM, "lincomatic" <notifications@github.com<mailto:notifications@github.com>> wrote:

I have RAPI interface code to contribute. Don't have time to figure out how to integrate it into your codebase. Who should I email it to?

**Comment by glynhudson** [comment]
@sandeen thanks a lot for the PR. Nice work. 

I've just replied to https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/5, I'm happy for my commit to be reversed to speed up RAPI updates.  

A slider to adjust charge rate and a button to pause / resume a charge would be awesome :+1: . Maybe a drop down box would work better than a slider since the user will probably be making the change using a mobile device. JS sliders can be hard to use, drop down boxes are handled well by mobile browsers. 

>  I've also seen occasional many-second stalls on the web page, and I have no idea what's causing them.

I've also noticed web page stalling issues. I've been in communication with @jeremypoulter who indicated the issue could be due to the ESP web server only being able to handle a single connection. He recommend changing to use the [Async web server](https://github.com/me-no-dev/ESPAsyncWebServer) and optimising the JS calls. 

@lincomatic sounds great, could post publicly on github so we could all review together?

**Pull request merged**
