### PR TITLE
Divert mode back-port

### PR DESCRIPTION
**Pull request by jeremypoulter**
Back-port of the PV divert changes from the ESP32 version ([ESP32 V3.2.0 change log](https://github.com/OpenEVSE/ESP32_WiFi_V3.x/releases/tag/3.2.0)), along with a few other fixes/improvements

- PV Divert changes
- Updates to save the config as a JSON block
- Python 3 fixes
- Latest GUI

Issues (see #259) :

- [x] Saving the Emoncms service hostname doesn't work, when I save a hostname e.g http://emonpi then look at output of /config the new hostname has not saved. It still shows the default emoncms_server: "https://data.openevse.com/emoncms",. emoncms_node saves correctly.
- [x] Hostname is openevse-000, I think we should just keep the hostname as it was as just http:/openevse to avoid confusing users who have been using their existing units with this default hostname.
- [x] After fresh reboot Eco Mode is enabled even though it had never been enabled previously, the UI toggle was showing 'Normal Mode' however /status was showing divertmode: 2,.
- [x] Available is incorrectly spelt available_current on published MQTT topic name, probably in other places also.
- [x] When EcoMode is enabled with Grid IE charging does not pause even if there is significant import from the Grid for a period of time. The same issue is present when Solar PV gen is selected and thre is 0W of solar PV Gen, charging does not pause
- [x] NTP option showing in UI
- [x] EmonCMS posting returns "Server error: -1"

### CODE REVIEW

**Comment by jeremypoulter** [comment]
@glynhudson 

>  Available is incorrectly spelt available_current on published MQTT topic name, probably in other places also.

I am not quite sure what the request is here, as far as I can see `available_current` is correct and what is used everywhere

**Comment by jeremypoulter** [comment]
Pushed a few fixes.

@glynhudson 
> After fresh reboot Eco Mode is enabled even though it had never been enabled previously, the UI toggle was showing 'Normal Mode' however /status was showing divertmode: 2,.

>  When EcoMode is enabled with Grid IE charging does not pause even if there is significant import from the Grid for a period of time. The same issue is present when Solar PV gen is selected and thre is 0W of solar PV Gen, charging does not pause

Can you reproduce these on the ESP32 as well?

**Comment by glynhudson** [comment]
Thanks a lot. 

> I am not quite sure what the request is here, as far as I can see `available_current` is correct and what is used everywhere

Sorry, my mistake. This is correct. 

>Can you reproduce these on the ESP32 as well?

No I can't I will double check.

**Comment by glynhudson** [comment]
Hi Jeremy, nice work. I've just tested all the issues above, and they all seem to be fixed :+1: 

Upon further testing the solar PV divert does seem to be working as expected, I was just getting caught out by the smoothing causing it not to react as fast as I was expecting, this is expected and desirable behaviour.

The only issue I seem to have at the moment is I can't get Emoncms to connect. I've tried emoncms.org, local emonPi via IP and hostname. All return `server error -1`

Screenshot from 2020-07-07 17-01-30

**Pull request merged**
