### PR TITLE
Changes to use ESPAsyncWebServer

### PR DESCRIPTION
**Pull request by jeremypoulter**
These changes change the webserver to [ESPAsyncWebServer ](https://github.com/me-no-dev/ESPAsyncWebServer). This web server can support more than the one connection that ESP8266WebServer supports and is just generally much faster.

### ESP8266WebServer
screenshot 2017-05-13 09 28 13

### ESPAsyncWebServer
screenshot 2017-05-13 09 30 06

### CODE REVIEW

**Comment by glynhudson** [comment]
Hi @jeremypoulter ,

Thanks a lot. I've just tested. The new web server is working great. Much improvement in loading times and multiple sessions using multiple devices seems to be handled ok.

Is there a reason why the hostname has been removed:

https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/e28a72040ecd5f06ec8cf53818d79bb0b5cefbf9/src/wifi.cpp#L19

It's really nice to be able to browse directly to http://openevse 

@chris1howell @sandeen after some more testing would you be happy for this PR to be merged?

**Comment by jeremypoulter** [comment]
> Is there a reason why the hostname has been removed:

It hasn't as far as I can see, where are you getting that from?

**Comment by sandeen** [comment]
I have not tested it yet, to be honest.  Will try to get to that, but don't let me hold things up.

I do wonder if an async webserver may make keeping serial comms straight tougher, unless we issue and parse each command synchronously - which may defeat some of the responsiveness work Jeremy has done.  What do you guys think?  I've been on the fence about how to proceed with the serial work overall.  I suppose just testing @lincomatic 's rapi library as-written is the place to start, and see what it does w.r.t. UI latency.

**Comment by jeremypoulter** [comment]
I have been thinking about this a bit, I did not like how the webserver just stomps over what ever anything else is doing. 

What we probably need to do is wrap all RAPI comms up in to a module, where all RAPI commands are placed on a queue, with a callback to call with the result. 

Then the main loop of the RAPI module will pull a command off the queue send it to the serial, read the result and call the callback. I think with some cleaver(ish) state management it should be possible to do this without blocking for too long.

**Comment by glynhudson** [comment]
Apologies, hostname is still working fine :+1: . 

The issue was that on my work network http://openevse.local is required, it's strange that on my home network http://openevse works fine.

**Comment by jeremypoulter** [comment]
Maybe the DHCP sets .local as the search domain on one router and not the
other?

**Comment by sandeen** [comment]
Running this in the garage now, seems good!

**Comment by sandeen** [comment]
I notice that you've commented out some of the text that was on the RAPI page but I think that's good, it always seemed extraneous.  The boxes in the table could lay out a bit better though now that the command input box is smaller, IMHO.

```
            <!--
            <p>Send RAPI Command</p>
            <p>Common Commands:</p>
            <p>Set Current - $SC XX</p>
            <p>Set Service Level - $SL 1 - $SL 2 - $SL A</p>
            <p>Get Real-time Current - $GG</p>
            <p>Get Temperatures - $GP</p>
            <p></p>
            -->
```

**Comment by chris1howell** [comment]
Phasing out RAPI is fine. It was only put there temporarily until a proper UI could be created. I planned to learn JavaScript to build it but have not made much progress.

On May 16, 2017 6:06 PM, "Eric Sandeen" <notifications@github.com<mailto:notifications@github.com>> wrote:

I notice that you've commented out some of the text that was on the RAPI page but I think that's good, it always seemed extraneous. The boxes in the table could lay out a bit better though now that the command input box is smaller, IMHO.

**Comment by sandeen** [comment]
RAPI tab is still there, it's just less wordy.  :)

**Pull request merged**
