### PR TITLE
HTML rework

### PR DESCRIPTION
**Pull request by jeremypoulter**
I have been working on some changes to serialize the HTTP requests to the ESP and generally simplify the Javascript.

### Changes

- Added the following JS libraries (~50KB when minimized and compressed);
  - [jQuery](https://jquery.com/): Mainly used as much nicer API to the XMLHttpRequest
  - [Knockout.js](http://knockoutjs.com/): Provides a MVVM architecture for JS, essentially allows splitting up of the data and display/UI. Within the context of this app it allows for the removal of the mostly duplicate code to fetch /status and /rapiupdate. The library manages the updating of the HTML depending on what has changed
- Fetches of /status and /rapiupdate (and /config) are serialized and added code to never duplicate requests, even if one gets delayed. 
- Removed the RAPI command iFrame to stop additional fetches. 
- Moved to an MVVM architecture, see above. This allows lots of code reuse, and removes a lot of the current duplicate code. It also vastly simplifies the updating of the HTML, this is all handled by Knockout.js.

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, nice the .js looks *much* cleaner. It was  bit of a nightmare to work on before. 

I like the option to run the js from a local file pointed at the ESP e.g. `var baseHost = 'openevse.local';`. This will be awesome for rapid dev 👍 

>The /status API returns some items that I would consider config (EmonCMS, MQTT, web UI user/password, etc), would it be ok to move these to the /config endpoint?

Yes, that's fine with me, makes sense. As you can see I have been removing security sensitive info e.g. passwords from being returned.

> The packets_success and packets_sent are duplicated on both the /status and /rapiupdate endpoints, any objection to removing the /status version?

Ah good spot. Removing them from `/rapiupdate` endpoint would keep things [consistent with EmonESP](https://github.com/openenergymonitor/EmonESP/blob/master/src/web_server.cpp#L279), however I'm not too worried either way. Definitely remove the duplicate!

**Comment by sandeen** [comment]
Big fan of jQuery, FWIW.
And yes, clarifying what's /config and what's /update would be great.  I think more and more needs to move towards live updates, TBH.

**Comment by jeremypoulter** [comment]
I would say the endpoints would be;
- /status - read-only system information, including WiFi status, EmonCMS/MQTT connection information, firmware version number 
- /config - writable system config, WiFi network, EmonCMS/MQTT/Ohm, OpenEVSE
- /rapiupdate - Live OpenEVSE system info

The REST purist in me would also get rid of all the /saveXXXX and change them to POSTs on the /config endpoint, but that is for another day ;-)

**Comment by sandeen** [comment]
Sorry about the conflicts w/ the other pull, I'll stay out of js/html for a while!

**Comment by jeremypoulter** [comment]
I have mostly completed this work, remaining;
- [ ] Merge with master
- [ ] Upgrade
- [ ] RAPI commands

If anyone can do some testing I would be grateful. Also is there anything to emulate the RAPI protocol on a PC?

**Comment by sandeen** [comment]
I'll give testing a shot.
The current RAPI loop is slow enough that you can enter responses yourself on the serial console.  ;)

**Comment by sandeen** [comment]
(Is the wifi blink status particularly useful?  The device is generally sealed inside the EVSE, and not visible...)

**Comment by chris1howell** [comment]
Cool I will load it up as well.

RAPI simulator is an interesting idea. I may try to whip one up in python.

**Comment by jeremypoulter** [comment]
> (Is the wifi blink status particularly useful? The device is generally sealed inside the EVSE, and not visible...)

Only when things stop working and you open the box ;-) but this was more of an aid for me as I have been working in a few locations and serves as a reminder that I need to reconfigure the WiFi

> Could this be something more descriptive like authenticationOK()? Or do you envision more than auth going into the preprocessing?

I originally added it like that as I was also (conditionally) adding the CORS headers to support the HTML running locally, but this header is added elsewhere (in what some would consider a security whole) so not needed.

**Comment by sandeen** [comment]
Somehow the "Rapi Command" got turned into a clickable button, is that intentional?
rapi_command

**Comment by sandeen** [comment]
Is there a way to tie the ko update period `var updateTime = 1 * 1000;` to the same variable that controls the RAPI update loop?  We do want to speed up that update loop, but right now the javascript is refreshing at 10x the rapi update speed.  :)  Is there much cost to poll /status & /rapiupdate once per second?

**Comment by jeremypoulter** [comment]
> Somehow the "RAPI Command" got turned into a clickable button, is that intentional?

Fixed

> Is there a way to tie the ko update period var updateTime = 1 * 1000; to the same variable that controls the RAPI update loop? We do want to speed up that update loop, but right now the javascript is refreshing at 10x the rapi update speed. :) Is there much cost to poll /status & /rapiupdate once per second?

This was just a debug change, I was going to change it back to 10s however I am not sure it adds much overhead so maybe it can stay as is. If we did want to sync with the RAPI update loop then we could get send the update time in the config or status responses and use that. 

Ideally thought we should move over to using WebSockets to push updates back to the client rather than polling, and ideally also having the OpenEVSE firmware push events via RAPI, but this is a bit more of a change than I would want to make right now.

**Comment by sandeen** [comment]
OpenEVSE does already send a couple of events, FWIW - state changes, and a request for wifi mode change (both of which we currently ignore in the wifi firmware).

**Comment by glynhudson** [comment]
Nice, just tested. The HTML and JS is *much* more responsive. Thanks a lot :+1: 

I'm will merge this, any bugs can be fixed as we go. I have created a V2.0.2 'stable' release prior to merging this PR: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/releases/tag/2.0.2

**Comment by sandeen** [comment]
Does the subscription on mode work?
```
  self.wifiConnecting = ko.observable(false);
  self.status.mode.subscribe(function (newValue) {
    console.log(newValue);
    if(newValue === "STA+AP" || newValue === "STA") {
      self.wifiConnecting(false);
    }
  });
```
I was trying to play with & learn KO a bit and was going to implement a wifi network change button; it seems to be working except that when the mode changes from STA to STA+AP after the new network is saved, things which depend on wifiConnecting _don't_ seem to change.  If I check /status I do see a new `"mode":"STA+AP"`, but I never see it printed with my added `console.log `above.  Apologies if this is to vague, I should probably push up a branch...

**Comment by sandeen** [comment]
Oh, duh.  The browser gets disconnected and so of course I don't see any updates.  Sorry for the noise.  (Not sure if there's a way to make it more graceful, though...)

**Pull request merged**
