### PR TITLE
Fixes to enable UI on non-standard HTTP ports

### PR DESCRIPTION
**Pull request by jeremypoulter**
Mainly to enable use use the simulator on a port > 1024 for OS that care about that kind of thing.

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks, that's great. This should also fix #121 and is a big step towards #70. 

This should now allow the wifi gateway to work over port forwarding. Adding a user config option to set the base port as suggested in #70 is an option but being able to forward web traffic to port 80 is a good start. 

e.g. this was the issue before when accessing over port forwarding

**Comment by glynhudson** [comment]
Interesting, I've just tested trying to access the wifi gateway via a port forward, I setup a port forward to the ESP on internal port 80 and external random port e.g. 85. Previously when I tested this the UI loaded but with lots of errors (see above). Now the UI does not load at all, the host does not even resolve. The request is obviously not getting passed through. Are you able to replicate this? #121 and #70 are not yet resolved. However #142 is a higher priority if this is not an easy fix. The intended functionality of this PR works great i.e the ability to run the simulator on another port other than 80. I've setup a dev instance at http://79.143.80.210:3000/. 

I'm hoping @chris1howell will be able to setup a demo on the openevse website e.g. https://demo.openevse.com/ ?

**Comment by chris1howell** [comment]
http://demo.openevse.com:3000 is working...  I kinda cheated and just pointed to your server. I do not think this is what you had in mind though.
I will work self hosting the page an one om my servers then change the pointer.

I am trying add a DNS SRV record to automatically send http port 80 to 3000. Is that the right way to do a port forward...? or is it better forward the domain / port  by editing the apache config?

On Thu, Feb 8, 2018 at 4:32 PM, Glyn Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Interesting, I've just tested trying to access the wifi gateway via a port forward, I setup a port forward to the ESP on internal port 80 and external random port e.g. 85. Previously when I tested this the UI loaded but with lots of errors (see above). Now the UI does not load at all, the host does not even resolve. The request is obviously not getting passed through. Are you able to replicate this? #121<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/121> and #70<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/70> are not yet resolved. However #142<https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/142> is a higher priority if this is not an easy fix. The intended functionality of this PR works great i.e the ability to run the simulator on another port other than 80. I've setup a dev instance at http://79.143.80.210:3000/.

I'm hoping @chris1howell<https://github.com/chris1howell> will be able to setup a demo on the openevse website e.g. https://demo.openevse.com/ ?

**Comment by jeremypoulter** [comment]
There is an example Apache config in the simulator dir:
https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/master/simulator/example-openevse-apache.conf

This will server all the static resource directly from Apache and proxy the
API calls to the Node.js

**Comment by glynhudson** [comment]
>http://demo.openevse.com:3000 is working...  I kinda cheated and just pointed to your server. I do not think this is what you had in mind though.

That's fine by me. I will setup my version to autoupdate to track latest master branch. Up to you if you want to change this to serve via apache. This would probably be better practice

**Pull request merged**
